context:
  version: "100.0.2"

package:
  name: franka_description
  version: ${{ version }}

source:
  git: https://github.com/JafarAbdi/franka_ros2.git
  tag: ${{ version }}
  patches:
    - delete_ament.patch

build:
  number: 1
  script: |
    cmake ${CMAKE_ARGS} -GNinja -DBUILD_TESTS=OFF \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          $SRC_DIR/franka_description
    ninja install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
