context:
  version: "0.4.0"

package:
  name: franka_description
  version: ${{ version }}

source:
  git: https://github.com/frankaemika/franka_description.git
  tag: ${{ version }}
  patches:
    - delete_ament.patch

build:
  number: 1
  script: |
    cmake ${CMAKE_ARGS} -GNinja -DBUILD_TESTS=OFF \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          $SRC_DIR/
    ninja install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
