[project]
name = "rattler-recipes"
version = "0.1.0"
description = "Add a short description here"
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
build = "rattler-build build --recipe-dir ."
upload = "rattler-build upload prefix --channel ramp "

[dependencies]
rattler-build = ">=0.15.0,<0.16"
