context:
  version: "0.2.2"
  build_number: 1

package:
  name: kortex_description
  version: ${{ version }}

source:
  git: https://github.com/Kinovarobotics/ros2_kortex.git
  rev: 97a0e7c9a2b7970f8de5830919e2fe0d7eea3bf6
  patches:
    - delete_ament.patch

build:
  number: ${{ build_number }}
  script: |
    cmake ${CMAKE_ARGS} -GNinja -DBUILD_TESTS=OFF \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          $SRC_DIR/kortex_description
    ninja install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
