context:
  # Latest version upstream is 0.0.1
  version: "0.0.2"

package:
  name: robotiq_description
  version: ${{ version }}

source:
  git: https://github.com/PickNikRobotics/ros2_robotiq_gripper.git
  rev: main
  patches:
    - delete_ament.patch
    - continuous_to_revolute.patch

build:
  number: 1
  script: |
    cmake ${CMAKE_ARGS} -GNinja -DBUILD_TESTS=OFF \
          -DCMAKE_INSTALL_PREFIX=$PREFIX \
          $SRC_DIR/robotiq_description
    ninja install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
